---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  #
  # Check out this FAQ as to why this is needed.
  # https://argoproj.github.io/argo-cd/faq/#why-are-resources-of-type-sealedsecret-stuck-in-the-progressing-state
  #
  resource.customizations.health.bitnami.com_SealedSecret: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Controller doesn't report resource status"
    return hs  