apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  #
  # In order to authenticate with the AWS API, the provider controllers need to have access to credentials. It could be an IAM User for AWS
  # Note that every Crossplane managed resource has a 'providerConfig' field which allows us to specify a separate ProviderConfig per Managed Resource.
  # This allows us to use IAM credentials that are limited in scope to perform the operations related to only that managed resource.
  # If 'providerConfigRef' is not specified for a Managed Resource, Crossplane will attempt to use a ProviderConfig named 'default'
  #
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-credentials
      key: credentials
